set_property SRC_FILE_INFO {cfile:C:/Vivado_Project/MAM_Project_Basys3/MAM_Project_Basys3.srcs/constrs_1/new/config.xdc rfile:../../../MAM_Project_Basys3.srcs/constrs_1/new/config.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk_in1_0]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports reset]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H1 [get_ports generator_lvds_valid_p_0]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H2 [get_ports generator_lvds_data_p_0]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G3 [get_ports generator_lvds_clk_p_0]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J3 [get_ports lvds_p_i_0]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L3 [get_ports lvds_v_p_i_0]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M2 [get_ports ext_clk_i_p_0]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/clk_wiz_1/inst/clk_out1]]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[0]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[1]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[2]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[3]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[4]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[5]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[6]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[7]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[8]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[9]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[10]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[11]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[12]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[13]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[14]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[15]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[16]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[17]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[18]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[19]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[20]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[21]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[22]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[23]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[24]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[25]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[26]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[27]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[28]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[29]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[30]} {design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tdata[31]}]]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tvalid]]
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tlast]]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_1 ila
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 1 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/clk [get_nets [list design_1_i/lvds2axis_0/U0/DUT_1/ext_clk]]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe0 [get_nets [list design_1_i/lvds2axis_0/U0/DUT_1/s_axis_tready]]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
