# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dds_compiler_0_0/design_1_dds_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dds_compiler_0_0 || ORIG_REF_NAME==design_1_dds_compiler_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_config_module_0_1/design_1_axis_config_module_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_config_module_0_1 || ORIG_REF_NAME==design_1_axis_config_module_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fir_compiler_0_0/design_1_fir_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_fir_compiler_0_0 || ORIG_REF_NAME==design_1_fir_compiler_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_analog_signal_genera_0_0/design_1_analog_signal_genera_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_analog_signal_genera_0_0 || ORIG_REF_NAME==design_1_analog_signal_genera_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fir_compiler_0_1/design_1_fir_compiler_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_fir_compiler_0_1 || ORIG_REF_NAME==design_1_fir_compiler_0_1} -quiet] -quiet

# XDC: c:/Vivado_Project/Filter/Filter.gen/sources_1/bd/design_1/design_1_ooc.xdc
