# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado_Projects/ip_repo/lvds_axis/lvds_axis_1.0/src/axis_data_fifo_0/axis_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_data_fifo_0 || ORIG_REF_NAME==axis_data_fifo_0} -quiet] -quiet

# IP: d:/Vivado_Projects/ip_repo/lvds_axis/lvds_axis_1.0/src/fifo_generator_0/fifo_generator_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: d:/Vivado_Projects/ip_repo/lvds_axis/lvds_axis_1.0/src/fifo_generator_0/fifo_generator_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Vivado_Projects/ip_repo/lvds_axis/lvds_axis_1.0/src/fifo_generator_0/fifo_generator_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
