# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado_Projects/Arithmetic/Arithmetic.srcs/sources_1/bd/design_1/ip/design_1_arithmetic_ip_0_1/design_1_arithmetic_ip_0_1.xci
# IP: The module: 'design_1_arithmetic_ip_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Vivado_Projects/Arithmetic/Arithmetic.srcs/sources_1/bd/design_1/ip/edit_arithmetic_ip_v1_0.srcs/sources_1/bd/design_1/ip/design_1_div_gen_0_0/design_1_div_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_div_gen_0_0 || ORIG_REF_NAME==design_1_div_gen_0_0} -quiet] -quiet

# XDC: d:/Vivado_Projects/Arithmetic/Arithmetic.srcs/sources_1/bd/design_1/ip/edit_arithmetic_ip_v1_0.srcs/sources_1/bd/design_1/design_1_ooc.xdc

# IP: d:/Vivado_Projects/Arithmetic/Arithmetic.srcs/sources_1/bd/design_1/ip/design_1_arithmetic_ip_0_1/design_1_arithmetic_ip_0_1.xci
# IP: The module: 'design_1_arithmetic_ip_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Vivado_Projects/Arithmetic/Arithmetic.srcs/sources_1/bd/design_1/ip/edit_arithmetic_ip_v1_0.srcs/sources_1/bd/design_1/ip/design_1_div_gen_0_0/design_1_div_gen_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_div_gen_0_0 || ORIG_REF_NAME==design_1_div_gen_0_0} -quiet] -quiet

# XDC: d:/Vivado_Projects/Arithmetic/Arithmetic.srcs/sources_1/bd/design_1/ip/edit_arithmetic_ip_v1_0.srcs/sources_1/bd/design_1/design_1_ooc.xdc
