# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Vivado_Project/ip_repo/lvds_axis_ip/lvds_axis_1_0/src/axis_data_fifo_0/axis_data_fifo_0.xci
# IP: The module: 'axis_data_fifo_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vivado_Project/ip_repo/lvds_axis_ip/lvds_axis_1_0/src/axis_data_fifo_0/axis_data_fifo_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_data_fifo_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Vivado_Project/ip_repo/lvds_axis_ip/lvds_axis_1_0/src/axis_data_fifo_0/axis_data_fifo_0.xci
# IP: The module: 'axis_data_fifo_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vivado_Project/ip_repo/lvds_axis_ip/lvds_axis_1_0/src/axis_data_fifo_0/axis_data_fifo_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_data_fifo_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
