# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado_Projects/DMA_Project/DMA_Project.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_3/design_1_axi_dma_0_3.xci
# IP: The module: 'design_1_axi_dma_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_Projects/DMA_Project/DMA_Project.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_3/design_1_axi_dma_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_0_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado_Projects/DMA_Project/DMA_Project.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_3/design_1_axi_dma_0_3_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado_Projects/DMA_Project/DMA_Project.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_3/design_1_axi_dma_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Vivado_Projects/DMA_Project/DMA_Project.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_3/design_1_axi_dma_0_3.xci
# IP: The module: 'design_1_axi_dma_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_Projects/DMA_Project/DMA_Project.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_3/design_1_axi_dma_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado_Projects/DMA_Project/DMA_Project.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_3/design_1_axi_dma_0_3_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado_Projects/DMA_Project/DMA_Project.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_3/design_1_axi_dma_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
